version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./DockerfileWEB
    ports:
      - "8910:8910"
  api:
    build:
      context: .
      dockerfile: ./DockerfileAPI
    ports:
      - "8911:8911"
    restart: always
#    command: yarn redwood serve api --apiRootPath api
    environment:
      - NODE_ENV=development
      - RUNTIME_ENV=dev
      - DATABASE_URL=postgres://postgres:password@postgres-server:5432/postgres
