// This file is autogenerated by Redwood and will be overwitten periodically

import { db } from 'src/lib/db'
import datamodel from 'src/models/datamodel'
import { RedwoodRecord } from '@redwoodjs/record'

RedwoodRecord.db = db
RedwoodRecord.schema = datamodel

import ExperimentResult from 'src/models/ExperimentResult'
import QaObject from 'src/models/QaObject'
import QaObjectRelationship from 'src/models/QaObjectRelationship'
import User from 'src/models/User'
import UserRole from 'src/models/UserRole'

ExperimentResult.requiredModels = []
QaObject.requiredModels = []
QaObjectRelationship.requiredModels = []
User.requiredModels = [UserRole]
UserRole.requiredModels = [User]

export { ExperimentResult, QaObject, QaObjectRelationship, User, UserRole }
