// This file is autogenerated by Redwood and will be overwitten periodically

import { db } from 'src/lib/db'
import datamodel from 'src/models/datamodel'
import { RedwoodRecord } from '@redwoodjs/record'

RedwoodRecord.db = db
RedwoodRecord.schema = datamodel

import Message from 'src/models/Message'
import QaObjectRelationship from 'src/models/QaObjectRelationship'

Message.requiredModels = []
QaObjectRelationship.requiredModels = []

export { Message, QaObjectRelationship }
